/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rozhrani;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import obce.IObyvatele;
import obce.Obec;
import obce.Obyvatele;
import obce.enumPozice;

/**
 *
 * @author Oldřich
 */
public class ProgObyvatele extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private IObyvatele obyvatele;

    public ProgObyvatele() {
        initComponents();
        cmbPozice.setModel(new DefaultComboBoxModel(enumPozice.values()));
        this.obyvatele = new Obyvatele();
        this.setSize(680, 461);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtaObsah = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnNacti = new javax.swing.JButton();
        btnUloz = new javax.swing.JButton();
        btnGeneruj = new javax.swing.JButton();
        btnRucne = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnZpristupni = new javax.swing.JButton();
        cmbPozice = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnOdeber = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spnKraj = new javax.swing.JSpinner();
        btnPrumer = new javax.swing.JButton();
        btnZobraz = new javax.swing.JButton();
        btnZobrazNadPrumer = new javax.swing.JButton();
        btnZrus = new javax.swing.JButton();
        btnUlozCSV = new javax.swing.JButton();
        btnUlozBin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        txtaObsah.setEditable(false);
        txtaObsah.setColumns(20);
        txtaObsah.setRows(5);
        txtaObsah.setText("Welcome");
        jScrollPane2.setViewportView(txtaObsah);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 110));

        btnNacti.setText("Nacti data ze souboru");
        btnNacti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNactiActionPerformed(evt);
            }
        });

        btnUloz.setText("Uloz vystup do souboru");
        btnUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozActionPerformed(evt);
            }
        });

        btnGeneruj.setText("Generuj data");
        btnGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerujActionPerformed(evt);
            }
        });

        btnRucne.setText("Vloz data rucne");
        btnRucne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRucneActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnZpristupni.setText("Zpristupni obec");
        btnZpristupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZpristupniActionPerformed(evt);
            }
        });

        cmbPozice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Vyberte pozici:");

        btnOdeber.setText("Odeber Obec");
        btnOdeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeberActionPerformed(evt);
            }
        });

        jLabel2.setText("Vyberte cislo kraje:");

        spnKraj.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        btnPrumer.setText("Zjisti prumer");
        btnPrumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrumerActionPerformed(evt);
            }
        });

        btnZobraz.setText("Zobraz obce");
        btnZobraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazActionPerformed(evt);
            }
        });

        btnZobrazNadPrumer.setText("Zobraz obce nad prumer");
        btnZobrazNadPrumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazNadPrumerActionPerformed(evt);
            }
        });

        btnZrus.setText("Zrus");
        btnZrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZrusActionPerformed(evt);
            }
        });

        btnUlozCSV.setText("Uloz data csv");
        btnUlozCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozCSVActionPerformed(evt);
            }
        });

        btnUlozBin.setText("Uloz data bin");
        btnUlozBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozBinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNacti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeneruj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRucne)
                            .addComponent(btnUlozCSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUlozBin)
                            .addComponent(btnUloz))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPozice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZpristupni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdeber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrumer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZobraz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZobrazNadPrumer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZrus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNacti)
                            .addComponent(btnGeneruj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRucne)
                            .addComponent(btnUloz)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPozice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(spnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZpristupni)
                            .addComponent(btnOdeber)
                            .addComponent(btnPrumer))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnZobraz)
                        .addComponent(btnZobrazNadPrumer)
                        .addComponent(btnZrus))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUlozCSV)
                        .addComponent(btnUlozBin)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNactiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNactiActionPerformed
        JFileChooser fc = new JFileChooser();
        txtaObsah.setText(null);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //System.out.println(fc.getSelectedFile().getPath());
            txtaObsah.setText("Nacteno " + obyvatele.importData(fc.getSelectedFile().getPath()) + " obci");

            //File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnNactiActionPerformed

    private void btnZobrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText(obyvatele.vratObce((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZobrazActionPerformed

    private void btnZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZrusActionPerformed
        txtaObsah.setText(null);
        obyvatele.zrus((Integer) spnKraj.getValue());
    }//GEN-LAST:event_btnZrusActionPerformed

    private void btnZobrazNadPrumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazNadPrumerActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText(obyvatele.vratObceNadPrumer((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZobrazNadPrumerActionPerformed

    private void btnPrumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrumerActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("prumer je " + obyvatele.zjistiPrumer((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnPrumerActionPerformed

    private void btnOdeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeberActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("odebrano:\n " + obyvatele.odeberObec((enumPozice) cmbPozice.getSelectedItem(), (Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnOdeberActionPerformed

    private void btnZpristupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZpristupniActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("zpristupneno:\n " + obyvatele.zpristupniObec((enumPozice) cmbPozice.getSelectedItem(), (Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZpristupniActionPerformed

    private void btnUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                //System.out.println(fc.getSelectedFile().getPath());
                BufferedWriter out = new BufferedWriter(new FileWriter(fc.getSelectedFile().getPath()));
                String ln = System.getProperty("line.separator");
                String text = txtaObsah.getText();
                text = text.replaceAll("\n", ln);
                out.write(text);
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(ProgObyvatele.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozActionPerformed

    private void btnRucneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRucneActionPerformed
        Novy novaObec = new Novy(obyvatele);
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, novaObec, "Vlozit rucne", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
//        if (showConfirmDialog == JOptionPane.OK_OPTION) {
//            System.out.println("ok - Obec");
//
//        }
    }//GEN-LAST:event_btnRucneActionPerformed

    private void btnUlozCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            obyvatele.ulozDataCsv(fc.getSelectedFile().getPath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozCSVActionPerformed

    private void btnGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerujActionPerformed
        txtaObsah.setText(null);
        obyvatele.zrus(0);
        int pocetZaznamu = 0;
        int pocetKraju = Generator.generujCislo(2, 20);
        for (int kraj = 1; kraj <= pocetKraju; kraj++) {
            obyvatele.vytvorKraj(Generator.generujNazev());
            int pocetObci = Generator.generujCislo(2, 10);
            pocetZaznamu += pocetObci;
            for (int obec = 0; obec < pocetObci; obec++) {
                obyvatele.vlozObec(Generator.generujObec(), enumPozice.POSLEDNI, kraj);
            }
        }
        txtaObsah.setText("vygenerovano " + pocetKraju + " kraju, " + pocetZaznamu + " obci");

    }//GEN-LAST:event_btnGenerujActionPerformed

    private void btnUlozBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozBinActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(fc.getSelectedFile().getPath()))) {
                oos.writeObject(obyvatele);
            } catch (IOException ex) {
                Logger.getLogger(ProgObyvatele.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            //log.append("Open command cancelled by user." + newline);
        }


    }//GEN-LAST:event_btnUlozBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgObyvatele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgObyvatele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgObyvatele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgObyvatele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgObyvatele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneruj;
    private javax.swing.JButton btnNacti;
    private javax.swing.JButton btnOdeber;
    private javax.swing.JButton btnPrumer;
    private javax.swing.JButton btnRucne;
    private javax.swing.JButton btnUloz;
    private javax.swing.JButton btnUlozBin;
    private javax.swing.JButton btnUlozCSV;
    private javax.swing.JButton btnZobraz;
    private javax.swing.JButton btnZobrazNadPrumer;
    private javax.swing.JButton btnZpristupni;
    private javax.swing.JButton btnZrus;
    private javax.swing.JComboBox cmbPozice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spnKraj;
    private javax.swing.JTextArea txtaObsah;
    // End of variables declaration//GEN-END:variables
}
