/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rozhrani;

import bvs.ETypProhl;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import obce.*;

/**
 *
 * @author Oldřich
 */
public class ProgAgendaKraj extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private IAgendaKraj agenda;

    public ProgAgendaKraj() {
        initComponents();
        cmbSousedni.setModel(new DefaultComboBoxModel(ETyp.values()));
        cmbSousedni.setSelectedItem(ETyp.AKTUALNI);
        cmbProhlidka.setModel(new DefaultComboBoxModel(ETypProhl.values()));
        cmbProhlidka.setSelectedItem(ETypProhl.HLOUBKY);
        this.agenda = new AgendaKraj();
        this.setSize(800, 461);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtaObsah = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnNacti = new javax.swing.JButton();
        btnUloz = new javax.swing.JButton();
        btnGeneruj = new javax.swing.JButton();
        btnRucne = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnOdeber = new javax.swing.JButton();
        btnZobraz = new javax.swing.JButton();
        btnUlozCSV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtObec = new javax.swing.JTextField();
        btnNajdi = new javax.swing.JButton();
        cmbProhlidka = new javax.swing.JComboBox();
        btnZobrazSousedni = new javax.swing.JButton();
        cmbSousedni = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtaObsah.setEditable(false);
        txtaObsah.setColumns(20);
        txtaObsah.setRows(5);
        txtaObsah.setText("Welcome");
        jScrollPane2.setViewportView(txtaObsah);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 110));

        btnNacti.setText("Nacti data ze souboru");
        btnNacti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNactiActionPerformed(evt);
            }
        });

        btnUloz.setText("Uloz vystup do souboru");
        btnUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozActionPerformed(evt);
            }
        });

        btnGeneruj.setText("Generuj data");
        btnGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerujActionPerformed(evt);
            }
        });

        btnRucne.setText("Vloz data");
        btnRucne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRucneActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnOdeber.setText("Odeber Obec");
        btnOdeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeberActionPerformed(evt);
            }
        });

        btnZobraz.setText("Zobraz obce");
        btnZobraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazActionPerformed(evt);
            }
        });

        btnUlozCSV.setText("Uloz data csv");
        btnUlozCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozCSVActionPerformed(evt);
            }
        });

        jLabel3.setText("Zadejte nazev:");

        txtObec.setText("Obec");

        btnNajdi.setText("Najdi obec");
        btnNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNajdiActionPerformed(evt);
            }
        });

        cmbProhlidka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnZobrazSousedni.setText("Zpristupni");
        btnZobrazSousedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazSousedniActionPerformed(evt);
            }
        });

        cmbSousedni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRucne)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNacti, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGeneruj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUlozCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(btnUloz)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNajdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZobraz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOdeber)
                            .addComponent(cmbProhlidka, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnZobrazSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cmbSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObec)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNacti)
                            .addComponent(btnGeneruj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRucne)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUlozCSV)
                            .addComponent(btnUloz))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtObec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNajdi)
                            .addComponent(btnOdeber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProhlidka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZobraz)
                            .addComponent(btnZobrazSousedni)
                            .addComponent(cmbSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNactiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNactiActionPerformed
        JFileChooser fc = new JFileChooser();
        txtaObsah.setText(null);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            agenda = new AgendaKraj();
            //System.out.println(fc.getSelectedFile().getPath());
            txtaObsah.setText("Nacteno " + agenda.importData(fc.getSelectedFile().getPath()) + " obci");

            //File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnNactiActionPerformed

    private void btnZobrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazActionPerformed
        txtaObsah.setText(null);
        String text = "";
        Iterator<IKlic> iterator = agenda.VytvorIterátor((ETypProhl) cmbProhlidka.getSelectedItem());
        if (!iterator.hasNext()) {
            text = "neni co vypsat" + System.getProperty("line.separator");
        }
        int pocet = 0;
        while (iterator.hasNext()) {
            text += iterator.next().toString();
            text += System.getProperty("line.separator");
            pocet++;
        }
        text += "vypsano " + pocet + " obci" + System.getProperty("line.separator");
        txtaObsah.setText(text);
    }//GEN-LAST:event_btnZobrazActionPerformed

    private void btnOdeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeberActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("odebrano:\n " + agenda.getPosledni());
        agenda.Odeber();
    }//GEN-LAST:event_btnOdeberActionPerformed

    private void btnUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                //System.out.println(fc.getSelectedFile().getPath());
                BufferedWriter out = new BufferedWriter(new FileWriter(fc.getSelectedFile().getPath()));
                String ln = System.getProperty("line.separator");
                String text = txtaObsah.getText();
                text = text.replaceAll("\n", ln);
                out.write(text);
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(ProgAgendaKraj.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozActionPerformed

    private void btnRucneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRucneActionPerformed
        Novy novaObec = new Novy(agenda);
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, novaObec, "Vlozit rucne", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
//        if (showConfirmDialog == JOptionPane.OK_OPTION) {
//            System.out.println("ok - Obec");
//
//        }
    }//GEN-LAST:event_btnRucneActionPerformed

    private void btnUlozCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            agenda.ulozDataCsv(fc.getSelectedFile().getPath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozCSVActionPerformed

    private void btnGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerujActionPerformed
        txtaObsah.setText(null);
        agenda = new AgendaKraj();
        int pocetZaznamu = 0;
        int pocetKraju = Generator.generujCislo(2, 20);
        for (int kraj = 1; kraj <= pocetKraju; kraj++) {
            agenda.vytvorKraj(Generator.generujNazev());
            int pocetObci = Generator.generujCislo(2, 10);
            pocetZaznamu += pocetObci;
            for (int obec = 0; obec < pocetObci; obec++) {
                IObec nova = Generator.generujObec(pocetKraju);
                nova.setKraj(kraj);
                agenda.Vloz(nova);
            }
        }
        txtaObsah.setText("vygenerovano " + pocetKraju + " kraju, " + pocetZaznamu + " obci");

    }//GEN-LAST:event_btnGenerujActionPerformed

    private void btnNajdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNajdiActionPerformed
        IObec obec = new Obec(0, txtObec.getText(), 0);
        agenda.Najdi(obec);
        txtaObsah.setText(null);
        txtaObsah.setText("nalezeno: " + agenda.getPosledni());
    }//GEN-LAST:event_btnNajdiActionPerformed

    private void btnZobrazSousedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazSousedniActionPerformed
        txtaObsah.setText(null);
        IObec obec = agenda.ZjistiSousedniObec((ETyp) cmbSousedni.getSelectedItem());
        if (obec != null) {
            txtaObsah.setText(obec.toString());
        } else {
            txtaObsah.setText("nebyla nalezena!");
        }
    }//GEN-LAST:event_btnZobrazSousedniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgAgendaKraj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneruj;
    private javax.swing.JButton btnNacti;
    private javax.swing.JButton btnNajdi;
    private javax.swing.JButton btnOdeber;
    private javax.swing.JButton btnRucne;
    private javax.swing.JButton btnUloz;
    private javax.swing.JButton btnUlozCSV;
    private javax.swing.JButton btnZobraz;
    private javax.swing.JButton btnZobrazSousedni;
    private javax.swing.JComboBox cmbProhlidka;
    private javax.swing.JComboBox cmbSousedni;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtObec;
    private javax.swing.JTextArea txtaObsah;
    // End of variables declaration//GEN-END:variables
}
