/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rozhrani;

import bvs.ETypProhl;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import obce.*;
import heap.*;
import java.util.Comparator;

/**
 *
 * @author Oldřich
 */
public class ProgAgendaKraj extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private IAbstrHeap<IObec> fronta;
    private IAgendaKraj agenda;
    private IObyvatele obyvatele;

    public ProgAgendaKraj() {
        initComponents();
        cmbSousedni.setModel(new DefaultComboBoxModel(ETyp.values()));
        cmbSousedni.setSelectedItem(ETyp.AKTUALNI);
        cmbProhlidka.setModel(new DefaultComboBoxModel(ETypProhl.values()));
        cmbProhlidka.setSelectedItem(ETypProhl.HLOUBKY);
        cmbPozice.setModel(new DefaultComboBoxModel(enumPozice.values()));
        Object pole[] = {new KomparatorNazvu(), new KomparatorObyvatel()};
        cmbPriorita.setModel(new DefaultComboBoxModel(pole));
        this.fronta = new AbstrHeap<>((Comparator<IObec>) cmbPriorita.getSelectedItem());
        this.agenda = new AgendaKraj();
        this.obyvatele = new Obyvatele();
        this.setSize(900, 461);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtaObsah = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnNacti = new javax.swing.JButton();
        btnUloz = new javax.swing.JButton();
        btnGeneruj = new javax.swing.JButton();
        btnRucne = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnUlozCSV = new javax.swing.JButton();
        tabPnlOvladani = new javax.swing.JTabbedPane();
        pnlSemA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbPozice = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        spnKraj = new javax.swing.JSpinner();
        btnZpristupni = new javax.swing.JButton();
        btnOdeber1 = new javax.swing.JButton();
        btnPrumer = new javax.swing.JButton();
        btnZrus1 = new javax.swing.JButton();
        btnZobrazNadPrumer = new javax.swing.JButton();
        btnZobraz1 = new javax.swing.JButton();
        pnlSemB = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtObec = new javax.swing.JTextField();
        btnNajdi = new javax.swing.JButton();
        btnOdeber = new javax.swing.JButton();
        btnZobraz = new javax.swing.JButton();
        cmbProhlidka = new javax.swing.JComboBox();
        btnZobrazSousedni = new javax.swing.JButton();
        cmbSousedni = new javax.swing.JComboBox();
        pnlSemC = new javax.swing.JPanel();
        btnVybuduj = new javax.swing.JButton();
        btnReorganizuj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbPriorita = new javax.swing.JComboBox();
        btnZrus = new javax.swing.JButton();
        btnPrazdny = new javax.swing.JButton();
        btnOdeberMax = new javax.swing.JButton();
        btnZpristupniMax = new javax.swing.JButton();
        btnVypis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 206));

        txtaObsah.setEditable(false);
        txtaObsah.setColumns(20);
        txtaObsah.setRows(5);
        txtaObsah.setText("Welcome");
        jScrollPane2.setViewportView(txtaObsah);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 140));

        btnNacti.setText("Nacti data ze souboru");
        btnNacti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNactiActionPerformed(evt);
            }
        });

        btnUloz.setText("Uloz vystup do souboru");
        btnUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozActionPerformed(evt);
            }
        });

        btnGeneruj.setText("Generuj data");
        btnGeneruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerujActionPerformed(evt);
            }
        });

        btnRucne.setText("Vloz data");
        btnRucne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRucneActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnUlozCSV.setText("Uloz data csv");
        btnUlozCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozCSVActionPerformed(evt);
            }
        });

        jLabel2.setText("Vyberte pozici:");

        cmbPozice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Vyberte cislo kraje:");

        spnKraj.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        btnZpristupni.setText("Zpristupni obec");
        btnZpristupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZpristupniActionPerformed(evt);
            }
        });

        btnOdeber1.setText("Odeber Obec");
        btnOdeber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeber1ActionPerformed(evt);
            }
        });

        btnPrumer.setText("Zjisti prumer");
        btnPrumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrumerActionPerformed(evt);
            }
        });

        btnZrus1.setText("Zrus");
        btnZrus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZrus1ActionPerformed(evt);
            }
        });

        btnZobrazNadPrumer.setText("Zobraz obce nad prumer");
        btnZobrazNadPrumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazNadPrumerActionPerformed(evt);
            }
        });

        btnZobraz1.setText("Zobraz obce");
        btnZobraz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobraz1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSemALayout = new javax.swing.GroupLayout(pnlSemA);
        pnlSemA.setLayout(pnlSemALayout);
        pnlSemALayout.setHorizontalGroup(
            pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSemALayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPozice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSemALayout.createSequentialGroup()
                        .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnZobraz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZpristupni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSemALayout.createSequentialGroup()
                                .addComponent(btnOdeber1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrumer))
                            .addGroup(pnlSemALayout.createSequentialGroup()
                                .addComponent(btnZobrazNadPrumer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnZrus1)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pnlSemALayout.setVerticalGroup(
            pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPozice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(spnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZpristupni)
                    .addComponent(btnOdeber1)
                    .addComponent(btnPrumer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSemALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZobraz1)
                    .addComponent(btnZobrazNadPrumer)
                    .addComponent(btnZrus1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabPnlOvladani.addTab("A", pnlSemA);

        jLabel3.setText("Zadejte nazev:");

        txtObec.setText("Obec");

        btnNajdi.setText("Najdi obec");
        btnNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNajdiActionPerformed(evt);
            }
        });

        btnOdeber.setText("Odeber Obec");
        btnOdeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeberActionPerformed(evt);
            }
        });

        btnZobraz.setText("Zobraz obce");
        btnZobraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazActionPerformed(evt);
            }
        });

        cmbProhlidka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnZobrazSousedni.setText("Zpristupni");
        btnZobrazSousedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazSousedniActionPerformed(evt);
            }
        });

        cmbSousedni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlSemBLayout = new javax.swing.GroupLayout(pnlSemB);
        pnlSemB.setLayout(pnlSemBLayout);
        pnlSemBLayout.setHorizontalGroup(
            pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSemBLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObec)
                        .addGap(54, 54, 54))
                    .addGroup(pnlSemBLayout.createSequentialGroup()
                        .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNajdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZobraz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProhlidka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOdeber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(btnZobrazSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlSemBLayout.setVerticalGroup(
            pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtObec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNajdi)
                    .addComponent(btnOdeber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZobraz)
                    .addComponent(cmbProhlidka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZobrazSousedni)
                    .addComponent(cmbSousedni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tabPnlOvladani.addTab("B", pnlSemB);

        btnVybuduj.setText("Vybuduj");
        btnVybuduj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVybudujActionPerformed(evt);
            }
        });

        btnReorganizuj.setText("Reorganizuj");
        btnReorganizuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReorganizujActionPerformed(evt);
            }
        });

        jLabel1.setText("Priorita dle:");

        cmbPriorita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnZrus.setText("Zrus");
        btnZrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZrusActionPerformed(evt);
            }
        });

        btnPrazdny.setText("Je prazdny?");
        btnPrazdny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrazdnyActionPerformed(evt);
            }
        });

        btnOdeberMax.setText("Odeber max");
        btnOdeberMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeberMaxActionPerformed(evt);
            }
        });

        btnZpristupniMax.setText("Zpristupni max");
        btnZpristupniMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZpristupniMaxActionPerformed(evt);
            }
        });

        btnVypis.setText("Vypis");
        btnVypis.setMaximumSize(new java.awt.Dimension(103, 23));
        btnVypis.setMinimumSize(new java.awt.Dimension(103, 23));
        btnVypis.setPreferredSize(new java.awt.Dimension(103, 23));
        btnVypis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVypisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSemCLayout = new javax.swing.GroupLayout(pnlSemC);
        pnlSemC.setLayout(pnlSemCLayout);
        pnlSemCLayout.setHorizontalGroup(
            pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVybuduj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZrus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrazdny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOdeberMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReorganizuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSemCLayout.createSequentialGroup()
                        .addComponent(btnZpristupniMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVypis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSemCLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPriorita, 0, 228, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSemCLayout.setVerticalGroup(
            pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSemCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVybuduj)
                    .addComponent(btnReorganizuj)
                    .addComponent(jLabel1)
                    .addComponent(cmbPriorita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZrus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSemCLayout.createSequentialGroup()
                        .addGroup(pnlSemCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrazdny)
                            .addComponent(btnOdeberMax)
                            .addComponent(btnZpristupniMax))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(btnVypis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabPnlOvladani.addTab("C", pnlSemC);

        tabPnlOvladani.setSelectedIndex(2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRucne)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUlozCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(btnUloz)))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNacti, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeneruj, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPnlOvladani)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNacti)
                    .addComponent(btnGeneruj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRucne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUlozCSV)
                    .addComponent(btnUloz))
                .addContainerGap())
            .addComponent(tabPnlOvladani)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNactiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNactiActionPerformed
        JFileChooser fc = new JFileChooser();
        txtaObsah.setText(null);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            agenda = new AgendaKraj();
            //System.out.println(fc.getSelectedFile().getPath());
            txtaObsah.setText("Nacteno " + agenda.importData(fc.getSelectedFile().getPath()) + " obci");
            obyvatele.importData(fc.getSelectedFile().getPath());
            //File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            //log.append("Opening: " + file.getName() + "." + newline);
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnNactiActionPerformed

    private void btnUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                //System.out.println(fc.getSelectedFile().getPath());
                BufferedWriter out = new BufferedWriter(new FileWriter(fc.getSelectedFile().getPath()));
                String ln = System.getProperty("line.separator");
                String text = txtaObsah.getText();
                text = text.replaceAll("\n", ln);
                out.write(text);
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(ProgAgendaKraj.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozActionPerformed

    private void btnRucneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRucneActionPerformed
        Novy novaObec = new Novy(agenda, obyvatele);
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, novaObec, "Vlozit rucne", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
//        if (showConfirmDialog == JOptionPane.OK_OPTION) {
//            System.out.println("ok - Obec");
//
//        }
    }//GEN-LAST:event_btnRucneActionPerformed

    private void btnUlozCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozCSVActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            agenda.ulozDataCsv(fc.getSelectedFile().getPath());
        } else {
            //log.append("Open command cancelled by user." + newline);
        }
    }//GEN-LAST:event_btnUlozCSVActionPerformed

    private void btnGenerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerujActionPerformed
        txtaObsah.setText(null);
        agenda = new AgendaKraj();
        obyvatele = new Obyvatele();
        int pocetZaznamu = 0;
        int pocetKraju = Generator.generujCislo(2, 20);
        for (int kraj = 1; kraj <= pocetKraju; kraj++) {
            String nazevKraje = Generator.generujNazev();
            agenda.vytvorKraj(nazevKraje);
            obyvatele.vytvorKraj(nazevKraje);
            int pocetObci = Generator.generujCislo(2, 10);
            pocetZaznamu += pocetObci;
            for (int obec = 0; obec < pocetObci; obec++) {
                IObec nova = Generator.generujObec(pocetKraju);
                nova.setKraj(kraj);
                agenda.Vloz(nova);
                obyvatele.vlozObec(nova, enumPozice.POSLEDNI, kraj);
            }
        }
        txtaObsah.setText("vygenerovano " + pocetKraju + " kraju, " + pocetZaznamu + " obci");

    }//GEN-LAST:event_btnGenerujActionPerformed

    private void btnZobrazSousedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazSousedniActionPerformed
        txtaObsah.setText(null);
        IObec obec = agenda.ZjistiSousedniObec((ETyp) cmbSousedni.getSelectedItem());
        if (obec != null) {
            txtaObsah.setText(obec.toString());
        } else {
            txtaObsah.setText("nebyla nalezena!");
        }
    }//GEN-LAST:event_btnZobrazSousedniActionPerformed

    private void btnZobrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazActionPerformed
        txtaObsah.setText(null);
        String text = "";
        Iterator<IKlic> iterator = agenda.VytvorIterátor((ETypProhl) cmbProhlidka.getSelectedItem());
        if (!iterator.hasNext()) {
            text = "neni co vypsat" + System.getProperty("line.separator");
        }
        int pocet = 0;
        while (iterator.hasNext()) {
            text += iterator.next().toString();
            text += System.getProperty("line.separator");
            pocet++;
        }
        text += "vypsano " + pocet + " obci" + System.getProperty("line.separator");
        txtaObsah.setText(text);
    }//GEN-LAST:event_btnZobrazActionPerformed

    private void btnOdeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeberActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("odebrano:\n " + agenda.getPosledni());
        agenda.Odeber();
    }//GEN-LAST:event_btnOdeberActionPerformed

    private void btnNajdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNajdiActionPerformed
        IObec obec = new Obec(0, txtObec.getText(), 0);
        agenda.Najdi(obec);
        txtaObsah.setText(null);
        txtaObsah.setText("nalezeno: " + agenda.getPosledni());
    }//GEN-LAST:event_btnNajdiActionPerformed

    private void btnZrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZrusActionPerformed
        fronta.zrus();
        txtaObsah.setText("zruseno");
    }//GEN-LAST:event_btnZrusActionPerformed

    private void btnZpristupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZpristupniActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("zpristupneno:\n " + obyvatele.zpristupniObec((enumPozice) cmbPozice.getSelectedItem(), (Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZpristupniActionPerformed

    private void btnOdeber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeber1ActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("odebrano:\n " + obyvatele.odeberObec((enumPozice) cmbPozice.getSelectedItem(), (Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnOdeber1ActionPerformed

    private void btnPrumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrumerActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText("prumer je " + obyvatele.zjistiPrumer((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnPrumerActionPerformed

    private void btnZrus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZrus1ActionPerformed
        txtaObsah.setText(null);
        obyvatele.zrus((Integer) spnKraj.getValue());
        agenda = new AgendaKraj();
    }//GEN-LAST:event_btnZrus1ActionPerformed

    private void btnZobrazNadPrumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazNadPrumerActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText(obyvatele.vratObceNadPrumer((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZobrazNadPrumerActionPerformed

    private void btnZobraz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobraz1ActionPerformed
        txtaObsah.setText(null);
        txtaObsah.setText(obyvatele.vratObce((Integer) spnKraj.getValue()));
    }//GEN-LAST:event_btnZobraz1ActionPerformed

    private void btnVybudujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVybudujActionPerformed
        Iterator it = agenda.VytvorIterátor(ETypProhl.SIRKY);
        Comparator cmp = (Comparator) cmbPriorita.getSelectedItem();
        fronta.vybuduj(it, cmp);
        txtaObsah.setText("vybudovano pomocí: " + cmbPriorita.getSelectedItem());
    }//GEN-LAST:event_btnVybudujActionPerformed

    private void btnReorganizujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReorganizujActionPerformed
        fronta.reorganizuj((Comparator<IObec>) cmbPriorita.getSelectedItem());
        txtaObsah.setText("reorganizovano pomocí: " + cmbPriorita.getSelectedItem());
    }//GEN-LAST:event_btnReorganizujActionPerformed

    private void btnPrazdnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrazdnyActionPerformed
        txtaObsah.setText("je prazdny: " + fronta.jePrazdny());
    }//GEN-LAST:event_btnPrazdnyActionPerformed

    private void btnVypisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVypisActionPerformed
        txtaObsah.setText("obsah fronty:\n");
        txtaObsah.append(fronta.vrat());
    }//GEN-LAST:event_btnVypisActionPerformed

    private void btnZpristupniMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZpristupniMaxActionPerformed
        txtaObsah.setText("zpristupnen max:\n" + fronta.zpristupniMax());
    }//GEN-LAST:event_btnZpristupniMaxActionPerformed

    private void btnOdeberMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeberMaxActionPerformed
        txtaObsah.setText("odebran max:\n" + fronta.odeberMax());
    }//GEN-LAST:event_btnOdeberMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgAgendaKraj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgAgendaKraj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneruj;
    private javax.swing.JButton btnNacti;
    private javax.swing.JButton btnNajdi;
    private javax.swing.JButton btnOdeber;
    private javax.swing.JButton btnOdeber1;
    private javax.swing.JButton btnOdeberMax;
    private javax.swing.JButton btnPrazdny;
    private javax.swing.JButton btnPrumer;
    private javax.swing.JButton btnReorganizuj;
    private javax.swing.JButton btnRucne;
    private javax.swing.JButton btnUloz;
    private javax.swing.JButton btnUlozCSV;
    private javax.swing.JButton btnVybuduj;
    private javax.swing.JButton btnVypis;
    private javax.swing.JButton btnZobraz;
    private javax.swing.JButton btnZobraz1;
    private javax.swing.JButton btnZobrazNadPrumer;
    private javax.swing.JButton btnZobrazSousedni;
    private javax.swing.JButton btnZpristupni;
    private javax.swing.JButton btnZpristupniMax;
    private javax.swing.JButton btnZrus;
    private javax.swing.JButton btnZrus1;
    private javax.swing.JComboBox cmbPozice;
    private javax.swing.JComboBox cmbPriorita;
    private javax.swing.JComboBox cmbProhlidka;
    private javax.swing.JComboBox cmbSousedni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlSemA;
    private javax.swing.JPanel pnlSemB;
    private javax.swing.JPanel pnlSemC;
    private javax.swing.JSpinner spnKraj;
    private javax.swing.JTabbedPane tabPnlOvladani;
    private javax.swing.JTextField txtObec;
    private javax.swing.JTextArea txtaObsah;
    // End of variables declaration//GEN-END:variables
}
